server:
  port: 8081

#eureka服务提供方(provider)配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 将instance-id设置成ip:端口的形式

#开启hystrix断路器
feign:
  hystrix:
    enabled: true
#设置读取超时时间
ribbon.ReadTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
  threadpool:
    default:
      #并发执行的最大线程数,默认10
      coreSize: 400

#spring配置
spring:
  application:
    name: master-web #服务名称，在eureka注册中心显示
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      percentage: 1.0 #采样率

  #redis配置
  redis:
    host: 10.1.65.33
    port: 6379
    password: billon
    lettuce:
      pool:
        max-active: 1024
        max-idle: 200

  #rabbitmq配置
  rabbitmq:
    host: 10.1.65.33
    port: 5672
    username: billon
    password: billon

#暴露actuator相关endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

########自定义配置项########
billon:
  master-web:
    sid: e6b85f22ee50523d8fe41eea27a8b94a #内部服务id
  messageConvertFilterNull: true
  advice:
    token:
      enabled: true
      excludedUris:
        - '/auth/token/refresh'

#日志级别
logging:
  level:
    root: debug